import AppKit

/// Raycast `Icon` id (kebab-case) → an SF Symbol name. AppKit-only (no project types) so it compiles in
/// a standalone `swift` test. Explicit map for name-mismatches; else a dashes→dots transform IF that's a
/// real SF Symbol; else the raw id IF it's a valid SF Symbol; else a generic "app" placeholder (never nil
/// — so an unknown icon still shows a glyph).
enum IconSymbol {
    private static let map: [String: String] = [
        // Prior explicit cases from PaletteView.sfSymbol(for:)
        "circle":               "circle.fill",
        "star":                 "star.fill",
        "clipboard":            "doc.on.clipboard",
        "globe":                "globe",
        "window":               "macwindow",
        "calendar":             "calendar",
        "magnifying-glass":     "magnifyingglass",
        "app-window-grid-3x3":  "square.grid.3x3",
        "car":                  "car",
        "code":                 "chevron.left.forwardslash.chevron.right",
        "code-block":           "curlybraces",
        "credit-card":          "creditcard",
        "envelope":             "envelope",
        "fingerprint":          "touchid",
        "gift":                 "gift",
        "hard-drive":           "internaldrive",
        "heartbeat":            "waveform.path.ecg",
        "key":                  "key",
        "paperclip":            "paperclip",
        "repeat":               "repeat",
        "shield":               "shield",
        "star-circle":          "star.circle",
        "switch":               "switch.2",
        "terminal":             "terminal",
        "text":                 "text.alignleft",
        "tree":                 "leaf",
        "wallet":               "wallet.pass",
        "wifi":                 "wifi",
        "wifi-disabled":        "wifi.slash",
        "check-circle":         "checkmark.circle",
        "check":                "checkmark",
        // Additional name-mismatches (new)
        "check-list":           "checklist",
        "arrow-clockwise":      "arrow.clockwise",
        "arrow-counter-clockwise": "arrow.counterclockwise",
        "arrow-ne":             "arrow.up.right",
        "new-document":         "doc.badge.plus",
        "document":             "doc",
        "speaker-high":         "speaker.wave.3",
        "speaker-low":          "speaker.wave.1",
        "speaker-off":          "speaker.slash",
        "x-mark-circle":        "xmark.circle",
        "question-mark":        "questionmark",
        "light-bulb":           "lightbulb",
        "ellipsis":             "ellipsis",
        "house":                "house",
        "cog":                  "gearshape",
        "gear":                 "gearshape",
        "trophy":               "trophy",
        "warning":              "exclamationmark.triangle",
        "info":                 "info.circle",
        "bug":                  "ant",
        "wand":                 "wand.and.stars",
        "save-document":        "square.and.arrow.down",
        "redo":                 "arrow.uturn.forward",
        "undo":                 "arrow.uturn.backward",
        "reply":                "arrowshape.turn.up.left",
        "copy":                 "doc.on.doc",
        "download":             "arrow.down.circle",
        "upload":               "arrow.up.circle",
        "minus":                "minus",
        "stop":                 "stop.fill",
        "play":                 "play.fill",
        "power":                "power",
        "moon":                 "moon",
        "sun":                  "sun.max",
        "music":                "music.note",
        "phone":                "phone",
        "video":                "video",
        "message":              "message",
        "bell":                 "bell",
        "bolt":                 "bolt",
        "bookmark":             "bookmark",
        "heart":                "heart",
        "list":                 "list.bullet",
        "cloud":                "cloud",
        "pencil":               "pencil",
        // Additional members to improve ecosystem coverage
        "arrow-left":           "arrow.left",
        "arrow-right":          "arrow.right",
        "arrow-up":             "arrow.up",
        "arrow-down":           "arrow.down",
        "arrow-left-circle":    "arrow.left.circle",
        "arrow-right-circle":   "arrow.right.circle",
        "arrow-up-circle":      "arrow.up.circle",
        "arrow-down-circle":    "arrow.down.circle",
        "chevron-left":         "chevron.left",
        "chevron-right":        "chevron.right",
        "chevron-up":           "chevron.up",
        "chevron-down":         "chevron.down",
        "filter":               "line.3.horizontal.decrease.circle",
        "image":                "photo",
        "keyboard":             "keyboard",
        "layers":               "square.3.layers.3d",
        "map":                  "map",
        "maximize":             "arrow.up.left.and.arrow.down.right",
        "microphone":           "mic",
        "network":              "network",
        "pie-chart":            "chart.pie",
        "receipt":              "receipt",
        "ruler":                "ruler",
        "desktop":              "desktopcomputer",
        "coin":                 "dollarsign.circle",
        "mouse":                "cursorarrow",
        "person":               "person",
        "hashtag":              "number",
        "link":                 "link",
        "lock":                 "lock",
        "plus":                 "plus",
        "trash":                "trash",
        "eye":                  "eye",
        "tag":                  "tag",
        "folder":               "folder",
        "pin":                  "pin",
        "crypto":               "bitcoinsign.circle",
    ]

    static func sfName(for id: String) -> String {
        if let m = map[id] { return m }
        let dotted = id.replacingOccurrences(of: "-", with: ".")
        if NSImage(systemSymbolName: dotted, accessibilityDescription: nil) != nil { return dotted }
        if NSImage(systemSymbolName: id, accessibilityDescription: nil) != nil { return id }
        return "app"
    }
}
